<a href="https://colab.research.google.com/github/pu-bi/AI-industry-job-experience-for-non-majors/blob/main/2-preprocess/preprocess_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 구글 드라이브 연결

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 해야할 것
1. pandas 임포트
2. 본인이 만든 original csv 파일 load
3. 발생했을 수 있는 문제점 하나씩 해결
  - dtype
  - NaN
  - 한 문장에 하나의 의도
  - 특수문자 제거
  - 앞, 뒤, 중복 공백 문자 처리
  - 글자수 필터링
  - 중복 데이터 삭제
4. 저장

### Pandas 임포트

In [ ]:
# pandas를 pd로 임포트 
import  as

### 본인의 데이터 로드
- pandas 라이브러리의 read_csv 활용해 데이터 로드

In [ ]:
# data path 할당
data_path = ""
# <> 부분을 채워 주세요. 
data_df = pd.<>(<>, index_col=0, header=0)

SyntaxError: ignored

In [ ]:
# 잘 load 되었는지 확인
data_df.head

,utt,날씨 묻기,관광지 추천,숙소 추천,맛집 추천,인사,소개,기타
1,제주도 날씨 어때?,1.0,0.0,0.0,0,0.0,0.0,0
2,제주도 현재 날씨 알려줘,1.0,0.0,0.0,0,0.0,0.0,0
3,제주도 관광지 추천 좀 해줄래?,0.0,1.0,0.0,0,0.0,0.0,0
4,제주 관광지 추천,0.0,1.0,0.0,0,0.0,0.0,0
5,제주 맛집 추천,0.0,0.0,0.0,1,0.0,0.0,0
6,제주 맛집 좀 추천해주라,0.0,0.0,0.0,1,0.0,0.0,0
7,숙소 추천해줄래?,0.0,0.0,1.0,0,0.0,0.0,0
8,숙소는 어디가 좋아?,0.0,0.0,1.0,0,0.0,0.0,0
9,안녕?,0.0,0.0,0.0,0,1.0,0.0,0
10,너 뭐 할줄 알아?,0.0,0.0,0.0,0,0.0,1.0,0
11,기능 알려줘,0.0,0.0,0.0,0,0.0,1.0,0
12,넌 이름이 뭐야?,1.0,0.0,0.0,0,1.0,0.0,0
13,오늘 얼마나 더워?,2.0,0.0,0.0,0,0.0,0.0,0
14,니가 할 수 있는게 있긴 해?,0.0,0.0,1.0,0,1.0,1.0,0
15,#$^ayeif안녕?,0.0,0.0,0.0,0,1.0,0.0,0
16,안녕?🤑,0.0,0.0,0.0,0,1.0,0.0,0
17,맛집 추천 좀 해주라 🤌,0.0,0.0,0.0,1,0.0,0.0,0
18,what is your name?,0.0,0.0,0.0,0,1.0,0.0,0
19,NaN,NaN,NaN,NaN,0,NaN,NaN,0
20,내가 생각하는 데이터는 공백을 제외한 길이가 최소 2개는 되어야 하고 최대 20글자...,0.0,0.0,0.0,0,0.0,0.0,1
21,야이 바보 멍청아,0.0,0.0,0.0,0,0.0,0.0,1
22,나는 배가 고프다,0.0,0.0,0.0,0,0.0,0.0,1
23,세상에 이런일이..,0.0,0.0,0.0,0,0.0,0.0,1
24,제주도는 날씨가 어떻게 돼?,1.0,0.0,0.0,0,0.0,0.0,0
25,상상하기도 싫어 싫어,0.0,0.0,0.0,0,0.0,0.0,1
26,내가 만약 외로울때면,0.0,0.0,0.0,0,0.0,0.0,1
27,제주도에는 어떤 관광지가 있어?,0.0,1.0,0.0,0,0.0,0.0,0
28,제주도 맛집 좀 골라주라,0.0,0.0,1.0,0,0.0,0.0,0
29,안녕 너 이름은 뭐야?,0.0,0.0,0.0,0,1.0,0.0,0
30,넌 할 줄 아는게 뭐야?,0.0,0.0,0.0,0,0.0,1.0,0
31,너 할 수 있는거 뭐 있냐?,0.0,0.0,0.0,0,0.0,1.0,0
32,내 이름이 뭐게?,0.0,0.0,0.0,0,0.0,0.0,1
33,넌 쓸모없어,0.0,0.0,0.0,0,0.0,0.0,1

##### Column 확인
- pandas.DataFrame.columns

In [ ]:
# <> 를 채워 넣어주세요.
data_df.<>

Index(['utt', '날씨 묻기', '관광지 추천', '숙소 추천', '맛집 추천', '인사', '소개', '기타'], dtype='object')

### 문제점
0. dtype
1. NaN
2. 두 개 이상의 의도
3. 특수기호
4. 중복공백
5. 글자수

### 데이터 정제 시작

#### dtype
- pandas.Series.astype

In [ ]:
# 각 컬럼의 type 확인
for head in data_df.columns:
  print(f'{head} type : {data_df[head].dtypes}')

utt type : object
날씨 묻기 type : float64
관광지 추천 type : float64
숙소 추천 type : float64
맛집 추천 type : int64
인사 type : float64
소개 type : float64
기타 type : int64

In [ ]:
# int64인 컬럼의 type을 float64로 변경
# <> 를 채워주세요.
data_df[<>] = data_df[<>].<>("float64")

In [ ]:
# 잘 변경되었는지 확인
for head in data_df.columns:
  print(f'{head} type : {data_df[head].dtypes}')

utt type : object
날씨 묻기 type : float64
관광지 추천 type : float64
숙소 추천 type : float64
맛집 추천 type : float64
인사 type : float64
소개 type : float64
기타 type : float64

#### NaN
- pandas.DataFrame.isna

In [ ]:
# NaN 이 있는지 확인
# <> 채우기
data_df.<>()

      utt  날씨 묻기  관광지 추천  숙소 추천  맛집 추천     인사     소개     기타
1   False  False   False  False  False  False  False  False
2   False  False   False  False  False  False  False  False
3   False  False   False  False  False  False  False  False
4   False  False   False  False  False  False  False  False
5   False  False   False  False  False  False  False  False
6   False  False   False  False  False  False  False  False
7   False  False   False  False  False  False  False  False
8   False  False   False  False  False  False  False  False
9   False  False   False  False  False  False  False  False
10  False  False   False  False  False  False  False  False
11  False  False   False  False  False  False  False  False
12  False  False   False  False  False  False  False  False
13  False  False   False  False  False  False  False  False
14  False  False   False  False  False  False  False  False
15  False  False   False  False  False  False  False  False
16  False  False   False  False  False  False  False  False
17  False  False   False  False  False  False  False  False
18  False  False   False  False  False  False  False  False
19   True   True    True   True  False   True   True  False
20  False  False   False  False  False  False  False  False
21  False  False   False  False  False  False  False  False
22  False  False   False  False  False  False  False  False
23  False  False   False  False  False  False  False  False
24  False  False   False  False  False  False  False  False
25  False  False   False  False  False  False  False  False
26  False  False   False  False  False  False  False  False
27  False  False   False  False  False  False  False  False
28  False  False   False  False  False  False  False  False
29  False  False   False  False  False  False  False  False
30  False  False   False  False  False  False  False  False
31  False  False   False  False  False  False  False  False
32  False  False   False  False  False  False  False  False
33  False  False   False  False  False  False  False  False

##### dropna
- pandas.DataFrame.dropna

In [ ]:
# NaN 이 포함된 row 버리기
# <> 채우기
data_df.<>(axis=0, inplace=True)

In [ ]:
# 잘 버려졌는지 확인
data_df.isna()

      utt  날씨 묻기  관광지 추천  숙소 추천  맛집 추천     인사     소개     기타
1   False  False   False  False  False  False  False  False
2   False  False   False  False  False  False  False  False
3   False  False   False  False  False  False  False  False
4   False  False   False  False  False  False  False  False
5   False  False   False  False  False  False  False  False
6   False  False   False  False  False  False  False  False
7   False  False   False  False  False  False  False  False
8   False  False   False  False  False  False  False  False
9   False  False   False  False  False  False  False  False
10  False  False   False  False  False  False  False  False
11  False  False   False  False  False  False  False  False
12  False  False   False  False  False  False  False  False
13  False  False   False  False  False  False  False  False
14  False  False   False  False  False  False  False  False
15  False  False   False  False  False  False  False  False
16  False  False   False  False  False  False  False  False
17  False  False   False  False  False  False  False  False
18  False  False   False  False  False  False  False  False
20  False  False   False  False  False  False  False  False
21  False  False   False  False  False  False  False  False
22  False  False   False  False  False  False  False  False
23  False  False   False  False  False  False  False  False
24  False  False   False  False  False  False  False  False
25  False  False   False  False  False  False  False  False
26  False  False   False  False  False  False  False  False
27  False  False   False  False  False  False  False  False
28  False  False   False  False  False  False  False  False
29  False  False   False  False  False  False  False  False
30  False  False   False  False  False  False  False  False
31  False  False   False  False  False  False  False  False
32  False  False   False  False  False  False  False  False
33  False  False   False  False  False  False  False  False

##### reset_index
index를 재설정

- pandas.DataFrame.reset_index

In [ ]:
# index 재설정
# <> 채우기
data_df.<>(drop=True, inplace=True)

#### 한 문장에 하나의 의도만 있는지 확인하기
- pandas.DataFrame.itertuples

In [ ]:
# for loop 돌며 잘못된 row 찾기
# <> 채우기
for row in data_df.<>():
  total_sum = sum(row[2:])
  if total_sum != 1:
    print(row)

Pandas(Index=11, utt='넌 이름이 뭐야?', _2=1.0, _3=0.0, _4=0.0, _5=0.0, 인사=1.0, 소개=0.0, 기타=0.0)
Pandas(Index=12, utt='오늘 얼마나 더워?', _2=2.0, _3=0.0, _4=0.0, _5=0.0, 인사=0.0, 소개=0.0, 기타=0.0)
Pandas(Index=13, utt='니가 할 수  있는게 있긴 해?', _2=0.0, _3=0.0, _4=1.0, _5=0.0, 인사=1.0, 소개=1.0, 기타=0.0)

for loop을 돌며 index정보를 가지고 삭제하자!

In [ ]:
# drop 이용해 삭제!
for row in data_df.itertuples():
  total_sum = sum(row[2:])
  if total_sum != 1:
    index = row[0]
    # <> 채우기
    data_df.<>(index, axis=0, inplace=True)

In [ ]:
# index 재설정
data_df.reset_index(drop=True, inplace=True)

,utt,날씨 묻기,관광지 추천,숙소 추천,맛집 추천,인사,소개,기타
0,제주도 날씨 어때?,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,제주도 현재 날씨 알려줘,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,제주도 관광지 추천 좀 해줄래?,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,제주 관광지 추천,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,제주 맛집 추천,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,제주 맛집 좀 추천해주라,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,숙소 추천해줄래?,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,숙소는 어디가 좋아?,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,안녕?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,너 뭐 할줄 알아?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,기능 알려줘,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,#$^ayeif안녕?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12,안녕?🤑,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,맛집 추천 좀 해주라 🤌,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,what is your name?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15,내가 생각하는 데이터는 공백을 제외한 길이가 최소 2개는 되어야 하고 최대 20글자...,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,야이 바보 멍청아,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,나는 배가 고프다,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,세상에 이런일이..,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,제주도는 날씨가 어떻게 돼?,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,상상하기도 싫어 싫어,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,내가 만약 외로울때면,0.0,0.0,0.0,0.0,0.0,0.0,1.0
22,제주도에는 어떤 관광지가 있어?,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,제주도 맛집 좀 골라주라,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,안녕 너 이름은 뭐야?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
25,넌 할 줄 아는게 뭐야?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
26,너 할 수 있는거 뭐 있냐?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
27,내 이름이 뭐게?,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,넌 쓸모없어,0.0,0.0,0.0,0.0,0.0,0.0,1.0

#### 텍스트 정제

In [ ]:
# 텍스트 확인
for row in data_df.itertuples():
  text = row[1]
  print(text)

제주도 날씨   어때?
제주도 현재 날씨 알려줘
제주도    관광지 추천 좀 해줄래?
제주 관광지 추천
제주 맛집 추천
제주 맛집 좀 추천해주라
숙소 추천해줄래?
숙소는 어디가 좋아?
안녕?
너 뭐 할줄 알아?
기능 알려줘
#$^ayeif안녕?
안녕?🤑
맛집 추천 좀 해주라 🤌
what is your name?
내가 생각하는 데이터는 공백을 제외한 길이가 최소 2개는 되어야 하고 최대 20글자는 넘지 않았으면 좋겠는데 너는 어떻게 생각해?
야이 바보 멍청아
나는 배가 고프다
세상에 이런일이..
제주도는 날씨가 어떻게 돼?
상상하기도 싫어 싫어
내가 만약 외로울때면
제주도에는 어떤 관광지가 있어?
제주도 맛집 좀 골라주라
안녕 너 이름은 뭐야?
  넌 할 줄 아는게 뭐야?
너 할 수 있는거 뭐 있냐?
내 이름이 뭐게?
넌 쓸모없어

##### 특수 문자 제거하기

###### 특수 문자 체크

In [ ]:
import re

special_character_list = list()

# 숫자, 한글, 공백, !?,. 제외하고 어떤 문자들이 있는지 확인
# <> 채우기
special = re.compile("[<>]")
special_list = list()

for row in data_df.itertuples():
  text = row[1]
  special_list.extend(re.findall(special, text))

set(special_list)

{'#',
 '$',
 '^',
 'a',
 'e',
 'f',
 'h',
 'i',
 'm',
 'n',
 'o',
 'r',
 's',
 't',
 'u',
 'w',
 'y',
 '\U0001f90c',
 '🤑'}

###### 특수문자 제거
- pandas.DataFrame.replace

In [ ]:
# replace 활용해 치환!
# <> 채우기
data_df.<>(regex=r'[<>]', value='', inplace=True)

In [ ]:
# 확인
data_df

,utt,날씨 묻기,관광지 추천,숙소 추천,맛집 추천,인사,소개,기타
0,제주도 날씨 어때?,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,제주도 현재 날씨 알려줘,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,제주도 관광지 추천 좀 해줄래?,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,제주 관광지 추천,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,제주 맛집 추천,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,제주 맛집 좀 추천해주라,0.0,0.0,0.0,1.0,0.0,0.0,0.0
6,숙소 추천해줄래?,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,숙소는 어디가 좋아?,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,안녕?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,너 뭐 할줄 알아?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10,기능 알려줘,0.0,0.0,0.0,0.0,0.0,1.0,0.0
11,안녕?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12,안녕?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13,맛집 추천 좀 해주라,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15,내가 생각하는 데이터는 공백을 제외한 길이가 최소 2개는 되어야 하고 최대 20글자...,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,야이 바보 멍청아,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,나는 배가 고프다,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,세상에 이런일이..,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,제주도는 날씨가 어떻게 돼?,1.0,0.0,0.0,0.0,0.0,0.0,0.0
20,상상하기도 싫어 싫어,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,내가 만약 외로울때면,0.0,0.0,0.0,0.0,0.0,0.0,1.0
22,제주도에는 어떤 관광지가 있어?,0.0,1.0,0.0,0.0,0.0,0.0,0.0
23,제주도 맛집 좀 골라주라,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,안녕 너 이름은 뭐야?,0.0,0.0,0.0,0.0,1.0,0.0,0.0
25,넌 할 줄 아는게 뭐야?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
26,너 할 수 있는거 뭐 있냐?,0.0,0.0,0.0,0.0,0.0,1.0,0.0
27,내 이름이 뭐게?,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,넌 쓸모없어,0.0,0.0,0.0,0.0,0.0,0.0,1.0

##### 앞, 뒤, 중복 공백 문자 처리하기

###### 공백문자 체크

In [ ]:
# 중복 공백, 앞, 뒤 공백 체크
# <> 채우기
double_space = re.compile('<>')
space_head = re.compile('<>')
space_tail = re.compile('<>')

# 공백 문제있는 utt 반환하는 함수 정의
def find_spaces(dataframe):
  for row in dataframe.itertuples():
    text = row[1]
    if re.findall(double_space, text):
      print(f"중복 공백 : {text}")
    if re.findall(space_head, text):
      print(f"앞 공백 : {text}")
    if re.findall(space_tail, text):
      print(f"뒷 공백 : {text}")

find_spaces(data_df)

중복 공백 : 제주도 날씨   어때?
중복 공백 : 제주도    관광지 추천 좀 해줄래?
뒷 공백 : 맛집 추천 좀 해주라
중복 공백 :    ?
앞 공백 :    ?
중복 공백 :   넌 할 줄 아는게 뭐야?
앞 공백 :   넌 할 줄 아는게 뭐야?
뒷 공백 :   넌 할 줄 아는게 뭐야?

###### 중복 공백 제거

In [ ]:
# replace, regex 활용해 중복 공백 -> 공백 하나로 치환
# <> 채우기
data_df.replace(regex="<>", value=" ", inplace=True)

In [ ]:
# 중복 공백 제거되었는지 확인
find_spaces(data_df)

뒷 공백 : 맛집 추천 좀 해주라
앞 공백 :  ?
앞 공백 :  넌 할 줄 아는게 뭐야?
뒷 공백 :  넌 할 줄 아는게 뭐야?

###### 앞, 뒤 공백 삭제
- pandas.Series.str.strip

In [ ]:
# df와 컬럼의 type 확인
print(f"train_df의 타입 : {type(data_df)}")
print()
# '' 안에 발화 컬럼 title을 입력해주세요. ex) utt
print(f"utt column의 타입 : {type(data_df[''])}")

train_df의 타입 : <class 'pandas.core.frame.DataFrame'>

utt column의 타입 : <class 'pandas.core.series.Series'>

In [ ]:
# 앞, 뒤 공백 삭제하기
# <> 채우기
# '' 안에 발화 컬럼 title을 입력해주세요. ex) utt
data_df[''] = data_df[''].str.strip()

In [ ]:
# 공백 문제 해결되었는지 확인
find_spaces(data_df)

###### 글자수 체크

In [ ]:
# 글자수 체크하는 함수 정의
def count_character(dataframe):
  for row in dataframe.itertuples():
    text = row[1]
    text = re.sub(' ', '', text)
    print(f"글자 수 : {len(text)}")

In [ ]:
count_character(data_df)

글자 수 : 8
글자 수 : 10
글자 수 : 13
글자 수 : 7
글자 수 : 6
글자 수 : 10
글자 수 : 8
글자 수 : 9
글자 수 : 3
글자 수 : 7
글자 수 : 5
글자 수 : 3
글자 수 : 3
글자 수 : 8
글자 수 : 1
글자 수 : 55
글자 수 : 7
글자 수 : 7
글자 수 : 9
글자 수 : 12
글자 수 : 9
글자 수 : 9
글자 수 : 14
글자 수 : 10
글자 수 : 9
글자 수 : 9
글자 수 : 10
글자 수 : 7
글자 수 : 5

###### 글자수 필터링
- 각자 적정 글자수 정하기
- 참고 : [pandas.Series.apply](https://pandas.pydata.org/docs/reference/api/pandas.Series.apply.html)

In [ ]:
# min = 최소 글자수, max = 최대 글자수
# <> 채우기
min = <>
max = <>
data_df = data_df[data_df["utt"].<>(lambda x: len(x) >= min) & data_df["utt"].<>(lambda x: len(x) <= max)]
data_df.reset_index(drop=True, inplace=True)

In [ ]:
# 확인
data_df

                  utt  날씨 묻기  관광지 추천  숙소 추천  맛집 추천   인사   소개   기타
0          제주도 날씨 어때?    1.0     0.0    0.0    0.0  0.0  0.0  0.0
1       제주도 현재 날씨 알려줘    1.0     0.0    0.0    0.0  0.0  0.0  0.0
2   제주도 관광지 추천 좀 해줄래?    0.0     1.0    0.0    0.0  0.0  0.0  0.0
3           제주 관광지 추천    0.0     1.0    0.0    0.0  0.0  0.0  0.0
4            제주 맛집 추천    0.0     0.0    0.0    1.0  0.0  0.0  0.0
5       제주 맛집 좀 추천해주라    0.0     0.0    0.0    1.0  0.0  0.0  0.0
6           숙소 추천해줄래?    0.0     0.0    1.0    0.0  0.0  0.0  0.0
7         숙소는 어디가 좋아?    0.0     0.0    1.0    0.0  0.0  0.0  0.0
8                 안녕?    0.0     0.0    0.0    0.0  1.0  0.0  0.0
9          너 뭐 할줄 알아?    0.0     0.0    0.0    0.0  0.0  1.0  0.0
10             기능 알려줘    0.0     0.0    0.0    0.0  0.0  1.0  0.0
11                안녕?    0.0     0.0    0.0    0.0  1.0  0.0  0.0
12                안녕?    0.0     0.0    0.0    0.0  1.0  0.0  0.0
13        맛집 추천 좀 해주라    0.0     0.0    0.0    1.0  0.0  0.0  0.0
14          야이 바보 멍청아    0.0     0.0    0.0    0.0  0.0  0.0  1.0
15          나는 배가 고프다    0.0     0.0    0.0    0.0  0.0  0.0  1.0
16         세상에 이런일이..    0.0     0.0    0.0    0.0  0.0  0.0  1.0
17    제주도는 날씨가 어떻게 돼?    1.0     0.0    0.0    0.0  0.0  0.0  0.0
18        상상하기도 싫어 싫어    0.0     0.0    0.0    0.0  0.0  0.0  1.0
19        내가 만약 외로울때면    0.0     0.0    0.0    0.0  0.0  0.0  1.0
20  제주도에는 어떤 관광지가 있어?    0.0     1.0    0.0    0.0  0.0  0.0  0.0
21      제주도 맛집 좀 골라주라    0.0     0.0    1.0    0.0  0.0  0.0  0.0
22       안녕 너 이름은 뭐야?    0.0     0.0    0.0    0.0  1.0  0.0  0.0
23      넌 할 줄 아는게 뭐야?    0.0     0.0    0.0    0.0  0.0  1.0  0.0
24    너 할 수 있는거 뭐 있냐?    0.0     0.0    0.0    0.0  0.0  1.0  0.0
25          내 이름이 뭐게?    0.0     0.0    0.0    0.0  0.0  0.0  1.0
26             넌 쓸모없어    0.0     0.0    0.0    0.0  0.0  0.0  1.0

#### 중복 제거!
- pandas.DataFrame.drop_duplicates

In [ ]:
# 중복된 데이터 제거
# <> 채우기
data_df.<>(inplace=True)
data_df.reset_index(drop=True, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

#### 저장!
- pandas.DataFrame.to_csv

In [ ]:
# 저장!
# <> 채우기
# "" 에는 저장할 파일의 위치를 적어주세요.
save_path = ""
data_df.<>(save_path)